### ISSUE TITLE
Although there is an error, it runs successfully, and the cracking speed is very slow

### ISSUE THREAD

**Issue by yangxin325** [BishopFox/unredacter#10]
## There is an error, and the cracking speed is very slow,like a snail.

npm start

> unredacter@1.0.0 start
> npm run build && electron ./dist/main.js

> unredacter@1.0.0 build
> tsc

(node:8300) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:20660) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

## Steps to Reproduce
First npm install, second npm start

### Additional context
Win10 , Desktop, Browser:Google Chrome vision 98.0.4758.102 , 2022.2.22 

### Relevant screenshots

![image](https://user-images.githubusercontent.com/30143274/155099324-6e04f5d7-b630-4c21-9176-c9ca9e3b8c82.png)
![image](https://user-images.githubusercontent.com/30143274/155099604-a67518f6-24a4-42c6-bcab-9656ee595e6b.png)

**Comment by yangxin325** [comment]
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code 1
npm ERR! path C:\Users\HUAWEI\Downloads\unredacter-main\node_modules\electron
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: read ECONNRESET
npm ERR!     at ClientRequest.<anonymous> (C:\Users\HUAWEI\Downloads\unredacter-main\node_modules\got\source\request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:640:26)
npm ERR!     at ClientRequest.emit (node:events:532:35)
npm ERR!     at ClientRequest.origin.emit (C:\Users\HUAWEI\Downloads\unredacter-main\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at TLSSocket.emit (node:events:520:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2022-02-26T09_17_13_337Z-debug-0.log


Subsequent installation errors occur in Windows PowerShell

**Comment by dan-bishopfox** [comment]
No idea what's up with those warnings. 

But in terms of speed, just how slow is "like a snail"? That's rather subjective. Can you try to guesstimate how many iterations per second you're getting?
